#include <iostream>
#include <conio.h>
using namespace std;

int main()
{
    cout << " ! HELLO, WORLD ! ";
    cout << " ! HELLO, WORLD ! ";
    cout << " ! HELLO, WORLD ! ";
    cout << " ! HELLO, WORLD ! ";
    cout << " ! HELLO, WORLD ! ";
    cout << " ! HELLO, WORLD ! ";
    cout << " ! HELLO, WORLD ! ";
    cout << " ! HELLO, WORLD ! ";
    cout << " ! HELLO, WORLD ! ";
    cout << " ! HELLO, WORLD ! ";
    cout << " ! HELLO, WORLD ! ";
    cout << " ! HELLO, WORLD ! ";
    cout << " ! HELLO, WORLD ! ";
    cout << " ! HELLO, WORLD ! ";
    cout << " ! HELLO, WORLD ! ";
    cout << " ! HELLO, WORLD ! ";
    cout << " ! HELLO, WORLD ! ";
    cout << " ! HELLO, WORLD ! ";
    cout << " ! HELLO, WORLD ! ";
    cout << " ! HELLO, WORLD ! ";
    cout << " ! HELLO, WORLD ! ";
    cout << " ! HELLO, WORLD ! ";
    cout << " ! HELLO, WORLD ! ";
    cout << " ! HELLO, WORLD ! ";
    cout << " ! HELLO, WORLD ! ";
    cout << " ! HELLO, WORLD ! ";
    cout << " ! HELLO, WORLD ! ";
    cout << " ! HELLO, WORLD ! ";
    cout << " ! HELLO, WORLD ! ";
    cout << " ! HELLO, WORLD ! ";
    cout << " ! HELLO, WORLD ! ";
    cout << " ! HELLO, WORLD ! ";
    cout << " ! HELLO, WORLD ! ";
    cout << " ! HELLO, WORLD ! ";
    cout << " ! HELLO, WORLD ! ";
    cout << " ! HELLO, WORLD ! ";
    cout << " ! HELLO, WORLD ! ";
    cout << " ! HELLO, WORLD ! ";
    cout << " ! HELLO, WORLD ! ";
    cout << " ! HELLO, WORLD ! ";
    cout << " ! HELLO, WORLD ! ";
    cout << " ! HELLO, WORLD ! ";
    cout << " ! HELLO, WORLD ! ";
    cout << " ! HELLO, WORLD ! ";
    cout << " ! HELLO, WORLD ! ";
    cout << " ! HELLO, WORLD ! ";
    cout << " ! HELLO, WORLD ! ";
    cout << " ! HELLO, WORLD ! ";
    cout << " ! HELLO, WORLD ! ";
    cout << " ! HELLO, WORLD ! ";
    cout << " ! HELLO, WORLD ! ";
    cout << " ! HELLO, WORLD ! ";
    cout << " ! HELLO, WORLD ! ";
    cout << " ! HELLO, WORLD ! ";
    cout << " ! HELLO, WORLD ! ";
    cout << " ! HELLO, WORLD ! ";
    cout << " ! HELLO, WORLD ! ";
    cout << " ! HELLO, WORLD ! ";
    cout << " ! HELLO, WORLD ! ";
    cout << " ! HELLO, WORLD ! ";
    cout << " ! HELLO, WORLD ! ";
    cout << " ! HELLO, WORLD ! ";
    cout << " ! HELLO, WORLD ! ";
    cout << " ! HELLO, WORLD ! ";
    cout << " ! HELLO, WORLD ! ";
    cout << " ! HELLO, WORLD ! ";
    cout << " ! HELLO, WORLD ! ";
    cout << " ! HELLO, WORLD ! ";
    cout << " ! HELLO, WORLD ! ";
    cout << " ! HELLO, WORLD ! ";
    cout << " ! HELLO, WORLD ! ";
    cout << " ! HELLO, WORLD ! ";
    cout << " ! HELLO, WORLD ! " << endl;
}
